baseURL = "https://www.pascom.net/doc"
theme = "dot"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
primaryColor = "#d20134"
secondaryColor = "#f9f9f9"
textColor = "#666666"
textColorDark = "#000000"
whiteColor = "#ffffff"


[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "pascom Documentation"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "images/logo_white.png"
  logoAlt = "images/logo.png"
  copyright = "Copyright © 2019 pascom.net"

    # navigation
    #[Languages.en.menu]
    #
    #    
    #  [[Languages.en.menu.main]]
    #    weight = 2
    #    name = "contact"
    #    url = "en/contact"
      

    # algolia
    [Languages.en.params]
    algoliaindex = "doc-productive-en"
    legalnoticeUrl = "legal-notice"

    # banner
    [Languages.en.params.banner]
      title = "Documentation"
      description = "pascom Product Documentation and Release Notes"

    # Topics
    [Languages.en.params.topics]
      title = "Categories"
    
    # call to action
    [Languages.en.params.cta]
      enable = true
      title = "Didn't find an answer to your question?"
      description = "Ask our support forum. We are here to help!"
      btnText = "Ask Our Support Forum"
      btnURL = "https://www.pascom.net/forum/tags/english"


    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "fab fa-facebook-f"
      linkURL = "http://www.facebook.com/pascom.net"

    [[Languages.en.socialIcon]]
      icon = "fab fa-twitter"
      linkURL = "http://twitter.com/pascom_net"
      
    [[Languages.en.socialIcon]]
      icon = "fab fa-youtube"
      linkURL = "http://www.youtube.com/user/pascomnet"



  # German Language
  [Languages.de]
  languageName = "De"
  weight = 1
  languageCode = "de"
  title = "PASCOM"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "images/logo_white.png"
  logoAlt = "images/logo.png"
  copyright = "Copyright © 2019 pascom.net"

    # navigation
    #[Languages.de.menu]
    # 

    #  [[Languages.de.menu.main]]
    #    weight = 2
    #    name = "contact"
    #    url = "de/contact"


    # algolia
    [Languages.de.params]
    algoliaindex = "doc-productive-de"
    legalnoticeUrl = "legal-notice"


    # banner
    [Languages.de.params.banner]
      title = "Dokumentation"
      description = "pascom Produkt Dokumentation und Release Notes"

        # Topics
    [Languages.de.params.topics]
      title = "Kategorien"
  
    
    # call to action
    [Languages.de.params.cta]
      enable = true
      title = "Keine Antwort auf Ihre Frage gefunden?"
      description = "Fragen Sie unser Support Forum. Wir sind hier um zu helfen!"
      btnText = "Support Forum Fragen"
      btnURL = "https://www.pascom.net/forum"

  
    # footer social icon
    [[Languages.de.socialIcon]]
      icon = "fab fa-facebook-f"
      linkURL = "http://www.facebook.com/pascom.net"

    [[Languages.de.socialIcon]]
      icon = "fab fa-twitter"
      linkURL = "http://twitter.com/pascom_net"
      
    [[Languages.de.socialIcon]]
      icon = "fab fa-youtube"
      linkURL = "http://www.youtube.com/user/pascomnet"