baseurl = "http://localhost:1313/"
languageCode = "en-EN"
title = "mobydick developer Documentation"
theme = "doc-pascom"
contentdir = "content"
canonifyurls = true


[params]

    # basurlde Link zur Startseite der Doku (bei der Deutschen Doku immer auf den ersten Artikel verlinken | bei der Englischen Doku immer Link ohne ersten Artikel)
    baseurlde = "https://www.pascom.net/en/documentation/developer"

    # baseurlen Notwendig f체r den Umschalter in die Englische Wiki
    baseurlen = "https://www.pascom.net/en/documentation/developer"

    # lang Variable damit der HMTL Header auch de oder en anzeigt
    lang = "en"

    # wikiurl Ist die BaseUrl der Wiki und muss entweder nach de oder en umgestellt werden. Kann auch sp채ter auf andere Sprachen umschalten
    wikiurl = "https://www.pascom.net/en/documentation/"
    wikiname= "Documentation"

    # handbook* definiert die Doku e.g. mobydick Handbuch, cloudstack, release notes,...
    handbookurl="developer"
    handbookname ="Developer"

    # Wir haben ein Men체 links, welches auf bestimmte Theme verweist. Die Inhalte der Variablen m체ssen dann auch immer entsprechend der Sprache angepasst werden.
    impressumtext = "Legal Notice"
    impressumurl = "https://www.pascom.net/en/legal-notice//"
    impressumtitle = "pascom Legal Notice/"


    mypascomurl = "https://my.pascom.net/"
    mypascomtext = "my.pascom.net"
    mypascomtitle = "To the my.pascom Portal"

    # URL pascom.net
    pascomurl = "https://www.pascom.net/en/"

    # URL community
    communityurl = "http://community.pascom.net/forum.php?langid=6"

    # docuname gibt den Namen der jeweiligen Dokumentation an
    docuname = "Developer Documentation"

    searchfield = "Search in developer docs (shortcut 's')"

    algoliaindex = "doc-developer-en"
