baseurl = "http://localhost:1313/"
languageCode = "de-DE"
title = "mobydick cloudstack Dokumentation"
theme = "doc-pascom"
contentdir = "content_de"
canonifyurls = true


[params]

    # basurlde Link zur Startseite der Doku (bei der Deutschen Doku immer auf den ersten Artikel verlinken | bei der Englischen Doku immer Link ohne ersten Artikel)
    baseurlde = "https://www.pascom.net/de/dokumentation/cloudstack"

    # baseurlen Notwendig für den Umschalter in die Englische Wiki
    baseurlen = "https://www.pascom.net/en/documentation/cloudstack"

    # lang Variable damit der HMTL Header auch de oder en anzeigt
    lang = "de"

    # wikiurl Ist die BaseUrl der Wiki und muss entweder nach de oder en umgestellt werden. Kann auch später auf andere Sprachen umschalten
    wikiurl= "https://www.pascom.net/de/dokumentation/"
    wikiname ="Dokumentation"

    # handbook* definiert die Doku e.g. mobydick Handbuch, cloudstack, release notes,...
    handbookurl="cloudstack"
    handbookname ="cloudstack"

    # Wir haben ein Menü links, welches auf bestimmte Theme verweist. Die Inhalte der Variablen müssen dann auch immer entsprechend der Sprache angepasst werden.
    furthertips = "Hilfreiche Links"
    impressumtext = "Impressum"
    impressumurl = "https://www.pascom.net/de/impressum/"
    impressumtitle = "pascom Impressum"


    mypascomurl = "https://my.pascom.net/"
    mypascomtext = "my.pascom.net"
    mypascomtitle = "Zum my.pascom Portal"

    # URL pascom.net
    pascomurl = "https://www.pascom.net/de/"

    # URL community
    communityurl = "http://community.pascom.net/forum.php?langid=3"

    # docuname gibt den Namen der jeweiligen Dokumentation an
    docuname = "Cloudstack Dokumentation"

    searchfield = "Suche in cloudstack Doku (Tastenkürzel 's')"

    algoliaindex = "doc-cloudstack-de"
